class UploadMap < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  mount_uploader :file, MapUploader

  # relationships .............................................................
  belongs_to :map

  belongs_to :user

  # validations ...............................................................
  # callbacks .................................................................
  before_save :update_attributes

  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

    def update_attributes
      if file.present? && file_changed?
        self.name         = file.file.filename
        self.size         = file.file.size
        self.content_type = file.file.content_type
      end
    end

end
