class User < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :maps

  has_many :upload_maps, dependent: :destroy

  # validations ...............................................................
  validates_presence_of :nickname

  validates_uniqueness_of :nickname

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enum role: [:author, :editor, :admin]

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

end
